import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

import Amplify, { Analytics, Storage, API, graphqlOperation, XR} from 'aws-amplify';
import awsconfig from './aws-exports';
import { Authenticator, withAuthenticator, S3Album } from 'aws-amplify-react';
import { SumerianScene } from 'aws-amplify-react';
import scene1Config from './sumerian_exports_c17e011ca07143f2ba504c90272ba87a.json'; // This file will be generated by the Sumerian AWS Console

Amplify.configure({
  ...awsconfig,
  XR: {
    region: 'us-east-1', // Sumerian region
    scenes: {
      Mlaai1: {
        // Friendly scene name
        sceneConfig: scene1Config // Scene configuration from Sumerian publish
      }
    }
  }
});

Storage.configure({ level: 'private' });

const listTodos = `query listTodos {
  listTodos{
    items{
      id
      name
      description
    }
  }
}`;

const addTodo = `mutation createTodo($name:String! $description: String!) {
  createTodo(input:{
    name:$name
    description:$description
  }){
    id
    name
    description
  }
}`;

class App extends Component {
	  uploadFile = (evt) => {
		const file = evt.target.files[0];
		const name = file.name;

		Storage.put(name, file).then(() => {
		  this.setState({ file: name });
		})
	  }

	  componentDidMount() {
		Analytics.record('Amplify_CLI');
	  }
	  
	  todoMutation = async () => {
		  const todoDetails = {
			name: 'Party tonight!',
			description: 'Amplify CLI rocks!'
		  };

		  const newTodo = await API.graphql(graphqlOperation(addTodo, todoDetails));
		  alert(JSON.stringify(newTodo));
		};

		listQuery = async () => {
		  console.log('listing todos');
		  const allTodos = await API.graphql(graphqlOperation(listTodos));
		  alert(JSON.stringify(allTodos));
		};

		post = async () => {
		  console.log('calling api');
		  const response = await API.post('mlaaiapp', '/items', {
			body: {
			  id: '1',
			  name: 'hello amplify!'
			}
		  });
		  alert(JSON.stringify(response, null, 2));
		};
		get = async () => {
		  console.log('calling api');
		  const response = await API.get('mlaaiapp', '/items/object/1');
		  alert(JSON.stringify(response, null, 2));
		};
		list = async () => {
		  console.log('calling api');
		  const response = await API.get('mlaaiapp', '/items/1');
		  alert(JSON.stringify(response, null, 2));
		};
		async loadAndStartScene() {
			const progressCallback = (progress) => {
				console.log(`Sumerian scene load progress: ${progress * 100}%`);
			}

			const sceneOptions = {
				progressCallback
			}
			
			await XR.loadScene("Mlaai1", "sumerian-scene-dom-id", sceneOptions);
			XR.start("Mlaai1");
		}
	render() {
  return (
    <div className="App">
      // sceneName: the configured friendly scene you would like to load
      <SumerianScene sceneName="Mlaai1" />
    </div>
  );
}
}

const signUpConfig = {
  header: 'Mlaai Sign Up',
  hideAllDefaults: true,
  defaultCountryCode: '1',
  signUpFields: [
    {
      label: 'User Name',
      key: 'username',
      required: true,
      displayOrder: 1,
      type: 'string'
    },
    {
      label: 'Password',
      key: 'password',
      required: true,
      displayOrder: 2,
      type: 'password'
    },
    {
      label: 'Email',
      key: 'email',
      required: true,
      displayOrder: 3,
      type: 'string'
    }
  ]
};
const usernameAttributes = 'User Name';


export default withAuthenticator(App, {
  signUpConfig,
  usernameAttributes
});
